### PR TITLE
Add NXS command

### PR DESCRIPTION
**Pull request by pierotofy**
Adds support for building NXS/NXZ files.

Work in progress.﻿

### CODE REVIEW

**Comment by HeDo88TH** [comment]
You could use a couple of regex to extract the obj dependencies

`mtllib\s(?<mtl>.*$)`

`map_[^\s]+\s(?<res>.*$)`

It will be less efficient because you have to read the entire file first (could be huge).

**Comment by pierotofy** [comment]
Much less efficient; OBJs can be hundreds of MB and you need ways to break early from the matching loop.

**Comment by pierotofy** [comment]
Ref https://github.com/DroneDB/Registry/pull/243

**Comment by HeDo88TH** [comment]
It works 👌

**Pull request merged**
