### PR TITLE
Add push and pull commands (fixes)

### PR DESCRIPTION
**Pull request by HeDo88TH**
Continues from https://github.com/DroneDB/DroneDB/pull/195
Both push and pull commands are completed. Here we can find new fixes and more test cases.

### CODE REVIEW

**Comment by HeDo88TH** [comment]
Closes #202

**Comment by pierotofy** [comment]
@HeDo88TH you cannot use `CURLOPT_NOPROGRESS` to display progress reports for pull; the download file function is used by other parts of the software (e.g. the DSM service):

```
ddb info EP-11-19055_0018_0014.JPG 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:-  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:-100 12581    0 12581    0     0   1168      0 --:--:--  0:00:10 --:--:--  3815
Path: file:///data/drone/cmparks/images/EP-11-19055_0018_0014.JPG
Type: GeoImage (3)
CameraPitch: -81.99749565124512
CameraRoll: -4.192246913909912
CameraYaw: 115.38033294677734
CaptureTime: 1495526918480.0
FocalLength: 10.21358291336693
FocalLength35: 28.0
Height: 3648
Make: senseFly
Model: S.O.D.A.
Orientation: 1
Sensor: sensefly s.o.d.a.
SensorHeight: 8.754499640028797
SensorWidth: 13.131749460043196
Width: 5472
Modified Time: 1527112044
Size: 8.67 MB
Point Geometry: [[39.20072972222, -6.177518611111, 293.63724] ]
Polygon Geometry: [[39.20295806695, -6.176441560217, 10] [39.20092568919, -6.175477526076, 10] [39.19950321235, -6.17848127693, 10] [39.20153559935, -6.179445316109, 10] [39.20295806695, -6.176441560217, 10] ]
```

It pollutes stdout and violates unix principles.

If you need to show progress report, you need to use the proper callbacks to show your progress (similar to `ddb share`).

**Comment by pierotofy** [comment]
Remember that every function in DDB is potentially part of a library call; we do not want to pollute stdout.

**Comment by HeDo88TH** [comment]
> Remember that every function in DDB is potentially part of a library call; we do not want to pollute stdout.

It was not intentional 🤦

**Comment by pierotofy** [comment]
No worries!

**Pull request merged**
