### PR TITLE
Add delta command

### PR DESCRIPTION
**Pull request by HeDo88TH**
Added support for delta command:

`ddb delta source [target] [-j format]`

where `source` and `target` (default `.`) are ddb folders and format is `json` or `text`.
It compares `source` with `target` and outputs the diff that applied to `target` turns it into `source`
Need to add tests and support for text format but the diff algo is there.

### CODE REVIEW

**Comment by pierotofy** [comment]
Nice! :+1: 

First issue:

[test.zip](https://github.com/DroneDB/DroneDB/files/5946532/test.zip)

`ddb delta a/ a/ --format json` (comparing a dataset to itself) should obviously need to changes, but returns:

```
{"adds":[],"copies":[["a.txt","b/c.txt"]],"removes":[]}
```

**Comment by pierotofy** [comment]
Minor thing, format `text` does not print new lines and also outputs "No changes" even when changes are needed?

```
[piero:/data/b] [.venv] $ ddb delta ../a
 + [Directory] abc - [Directory] 123No changes
```

Have you tested this?

**Comment by pierotofy** [comment]
I've fixed the format text.

**Comment by pierotofy** [comment]
Should the command return some errors if you pass invalid folders?

E.g. 

```
ddb delta jkldsajdlksa dsjakldjlkdas
```

Or

```
ddb delta dhsjkadjsakldjsakl
```

**Comment by HeDo88TH** [comment]
I fixed the text output format and new lines but I did not push it yesterday. I pushed it now but conflicted with https://github.com/DroneDB/DroneDB/pull/182/commits/2a9ef4768a86be3c9c886a49ed96972fc370d5a2. Now I've merged the two in https://github.com/DroneDB/DroneDB/pull/182/commits/7a101e41dfcaf0d6a029f817383e0fe3298d931d . It is your delta format @pierotofy  👍

**Comment by HeDo88TH** [comment]
> Should the command return some errors if you pass invalid folders?
> 
> E.g.
> 
> ```
> ddb delta jkldsajdlksa dsjakldjlkdas
> ```
> 
> Or
> 
> ```
> ddb delta dhsjkadjsakldjsakl
> ```

Yes, It should give an error because those are not valid ddb folders. It opens them using `ddb::open` that is able to detect if it's not a ddb folder

**Comment by pierotofy** [comment]
> Yes, It should give an error because those are not valid ddb folders. It opens them using ddb::open that is able to detect if it's not a ddb folder

It didn't when I tested it.

**Comment by pierotofy** [comment]
I've removed the `No changes` string from delta if there are no changes (unix semantics prefer that a command that does nothing shows nothing).

**Comment by HeDo88TH** [comment]
> I've removed the `No changes` string from delta if there are no changes (unix semantics prefer that a command that does nothing shows nothing).

It's ok for me!

**Comment by pierotofy** [comment]
Found the issue; `ddb::open`'s second parameter if set to `true` will traverse the directory tree up (not the desired behavior here).

**Comment by pierotofy** [comment]
Looks and works very nicely! I couldn't find any further problems. :+1: 

Good addition!

**Pull request merged**
