### PR TITLE
Init/Add/Remove bindings for Node.JS

### PR DESCRIPTION
**Pull request by pierotofy**
Adds some missing bindings to NodeJS.

Fixes some bugs.

### CODE REVIEW

**Comment by pierotofy** [comment]
I need more time to troubleshoot some weird memory issue on Ubuntu.

**Comment by HeDo88TH** [comment]
Some checks are still failing, is it safe to merge?

**Comment by pierotofy** [comment]
Mm, no, I'll try to fix it first. Ugh.

**Comment by pierotofy** [comment]
All clear, ready for review :+1:

**Pull request merged**
