### PR TITLE
Refactor of moveEntry and fixes + tests

### LINKED ISSUE #233: Renaming a file with an existing path obliterates the file
Ref https://github.com/DroneDB/Registry/issues/162
This depends on the current implementation of moveEntry

### PR DESCRIPTION
**Pull request by HeDo88TH**
- [x] Compiles on Windows
 - [x] Compiles on Linux
 - [x] Manual tests on Windows to confirm the functionality/command works
 - [x] Manual tests on Linux to confirm the functionality/command works
 - [x] Manual tests on commands/functionality that might have been affected by these changes.
 - [x] There are no styling changes to unrelated code.

Closes #233 and https://github.com/DroneDB/Registry/issues/162

### CODE REVIEW

**Comment by HeDo88TH** [comment]
Now moveEntry cannot move a folder on another folder. The user should delete the dest folder first. No behaviour changes when replacing / moving files.

**Comment by HeDo88TH** [comment]
https://github.com/DroneDB/DroneDB/pull/234/commits/0b7c3280ac74e04bfb591bd575be9a6f6a9e2747 Closes #235

**Comment by pierotofy** [comment]
> Now moveEntry cannot move a folder on another folder

So I can't move a folder to another folder? E.g. move `/a` to `/b` which should result in `/a/b`?

**Comment by HeDo88TH** [comment]
> > Now moveEntry cannot move a folder on another folder
> 
> So I can't move a folder to another folder? E.g. move `/a` to `/b` which should result in `/a/b`?

You can do it onlt if `/a/b` does not exist before the move.

**Comment by HeDo88TH** [comment]
Example:
```
test1.jpg
test2.jpg
a
a\dummy.jpg
b
b\pic.jpg
```
You can do
`move('a','a/b')`
result
```
test1.jpg
test2.jpg
a
a\dummy.jpg
a\b
a\b\pic.jpg
```
But what you cannot do is
`move('a','b')`
because target folder `b` already exists.

**Pull request merged**
