### PR TITLE
Fix tiler on windows

### PR DESCRIPTION
**Pull request by HeDo88TH**
The constructor of `Tiler `does not release the handle to `tif` file. 
I'm trying to pinpoint where it happens, can you check this out @pierotofy 
(I added the line `GDALClose(src);` but it makes the tests fail)

```
GDALDatasetH Tiler::createWarpedVRT(const GDALDatasetH &src,
                                    const OGRSpatialReferenceH &srs,
                                    GDALResampleAlg resampling) {
    // GDALDriverH vrtDrv = GDALGetDriverByName( "VRT" );
    // if (vrtDrv == nullptr) throw GDALException("Cannot create VRT driver");

    // std::string vrtFilename = "/vsimem/" + uuidv4() + ".vrt";
    // GDALDatasetH vrt = GDALCreateCopy(vrtDrv, vrtFilename.c_str(), src,
    // FALSE, nullptr, nullptr, nullptr);

    char *dstWkt;
    if (OSRExportToWkt(srs, &dstWkt) != OGRERR_NONE)
        throw GDALException("Cannot export dst WKT " + geotiffPath +
                            ". Is PROJ available?");
    const char *srcWkt = GDALGetProjectionRef(src);

    const GDALDatasetH warpedVrt = GDALAutoCreateWarpedVRT(
        src, srcWkt, dstWkt, resampling, 0.001, nullptr);
    if (warpedVrt == nullptr) throw GDALException("Cannot create warped VRT");

    GDALClose(src);

    return warpedVrt;
}
```

### CODE REVIEW

**Comment by pierotofy** [comment]
You're getting a `unknown file: error: SEH exception with code 0xc0000005`

I don't think you should close the warpedVRT. Check the handles at the end of the tiler generation routine https://github.com/DroneDB/DroneDB/blob/master/src/tiler.cpp#L62

**Comment by pierotofy** [comment]
Check that the destructor is being called: https://github.com/DroneDB/DroneDB/blob/master/src/tiler.cpp#L160

**Comment by HeDo88TH** [comment]
Got it!

**Comment by pierotofy** [comment]
You're the man. :+1:

**Pull request merged**
