### PR TITLE
File lock

### LINKED ISSUE #177: ddb tile fails when called multiple times on the same geoimage
To reproduce:
 - Use latest version of hub with parallel tile request support
 - Try to geoproject an image (click on map on an image with geoprojection information)
 - Zoom in/out

```
ERROR 1: Deleting /vsimem/translated.tif failed:
No such file or directory
ERROR 1: Deleting /vsimem/translated.tif failed:
No such file or directory
ERROR 1: Deleting /vsimem/translated.tif failed:
No such file or directory
ERROR 4: Unable to open /vsimem/translated.tif to obtain file list.
ERROR 4: Unable to open /vsimem/translated.tif to obtain file list.
corrupted size vs. prev_size
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by pierotofy**
Fixes #177 and #172 by implementing file locking. Multiple processes can request the same geoprojected tiles and will not geo-project the same file concurrently. Processes will wait for the lock to be released before continuing.

### CODE REVIEW

**Comment by pierotofy** [comment]
Need to fix #179 on Windows.

**Comment by pierotofy** [comment]
Fixes https://github.com/DroneDB/Registry/issues/62

**Comment by pierotofy** [comment]
I've switched to use std::mutex, since the DLL/nodejs process runs on the same space; this might become a problem if/when multiple worker processes can generate tiles. We can switch to a file lock then.

Ready for review.

**Comment by HeDo88TH** [comment]
Nice work!  Tested on linux 20.04

**Pull request merged**
