### PR TITLE
Rename meta --> properties, remove DatasetInfo

### LINKED ISSUE #272: Rename meta to properties
The current `meta` field should probably be renamed `properties`, while the work in #140 should present the values in `meta`.

### PR DESCRIPTION
**Pull request by pierotofy**
- [x] Compiles on Windows
 - [x] Compiles on Linux
 - [x] Manual tests on Windows to confirm the functionality/command works
 - [x] Manual tests on Linux to confirm the functionality/command works
 - [x] Manual tests on commands/functionality that might have been affected by these changes.
 - [x] There are no styling changes to unrelated code.

Closes #272

### CODE REVIEW

**Comment by pierotofy** [comment]
This WILL break Hub, maybe breaks the .NET bindings (?) so a PR is needed to rename references of `meta` to `properties`.

**Comment by pierotofy** [comment]
Ready for review.

**Comment by HeDo88TH** [comment]
I will merge this when I evaluate the impact on registry. Probably I will open a new PR on Registry with the required changes to make it work seamlessly.

**Comment by pierotofy** [comment]
How come we need to wait for Registry? Couldn't we just merge this and update Registry later?

**Pull request merged**
