### PR TITLE
Add NodeJS bindings for chattr, DroneDB public info via meta

### PR DESCRIPTION
**Pull request by pierotofy**
Also adds DroneDB entry size calculation, misc cleanup.

Now you can issue:

```
[piero:/data/test] $ ddb info . --format json
[{"depth":1,"meta":{"public":true},"mtime":1606227570,"path":"file:///data/test/.","size":4024770,"type":1}]
```

This is relevant to Registry; public visibility flag should be stored on ddb, not on Registry's tables.

### CODE REVIEW

**Comment by HeDo88TH** [comment]
Nice addition, I will add this feature to Registry in the next days

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
> Nice addition, I will add this feature to Registry in the next days

Make sure to follow's MiniReg's API definition for it!

**Comment by pierotofy** [comment]
https://github.com/DroneDB/MiniReg/blob/master/index.js#L82

**Pull request merged**
