### PR TITLE
Add EPT command (Untwine)

### PR DESCRIPTION
**Pull request by pierotofy**
Adds the `ddb ept` command for generating EPT tilesets from point clouds.

### CODE REVIEW

**Comment by pierotofy** [comment]
This is ready for review.

By the way, I'm getting a bunch of failed tests on Linux for:

```
[  PASSED  ] 8 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] applyDeltaTest.simpleAdd
[  FAILED  ] applyDeltaTest.complexTree2
[  FAILED  ] applyDeltaTest.hardRename2
[  FAILED  ] applyDeltaTest.deepTree2
[  FAILED  ] applyDeltaTest.deepTree3
[  FAILED  ] applyDeltaTest.edgeCase2
[  FAILED  ] applyDeltaTest.hardNames2
[  FAILED  ] applyDeltaTest.edgeCase4
```

**Comment by HeDo88TH** [comment]
> This is ready for review.
> 
> By the way, I'm getting a bunch of failed tests on Linux for:
> 
> ```
> [  PASSED  ] 8 tests.
> [  FAILED  ] 8 tests, listed below:
> [  FAILED  ] applyDeltaTest.simpleAdd
> [  FAILED  ] applyDeltaTest.complexTree2
> [  FAILED  ] applyDeltaTest.hardRename2
> [  FAILED  ] applyDeltaTest.deepTree2
> [  FAILED  ] applyDeltaTest.deepTree3
> [  FAILED  ] applyDeltaTest.edgeCase2
> [  FAILED  ] applyDeltaTest.hardNames2
> [  FAILED  ] applyDeltaTest.edgeCase4
> ```
> 
> These are due to #195


> This is ready for review.
> 
> By the way, I'm getting a bunch of failed tests on Linux for:
> 
> ```
> [  PASSED  ] 8 tests.
> [  FAILED  ] 8 tests, listed below:
> [  FAILED  ] applyDeltaTest.simpleAdd
> [  FAILED  ] applyDeltaTest.complexTree2
> [  FAILED  ] applyDeltaTest.hardRename2
> [  FAILED  ] applyDeltaTest.deepTree2
> [  FAILED  ] applyDeltaTest.deepTree3
> [  FAILED  ] applyDeltaTest.edgeCase2
> [  FAILED  ] applyDeltaTest.hardNames2
> [  FAILED  ] applyDeltaTest.edgeCase4
> ```
> 
> These are due to #195

The CI says

```
D:\a\DroneDB\DroneDB\vendor\untwine\epf\FileProcessor.cpp(77,1): error C3493: 'CountIncrement' cannot be implicitly captured because no default capture mode has been specified [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
  Grid.cpp
  Reprocessor.cpp
  Writer.cpp
  MapFile.cpp
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(50,18): error C2039: '_open': is not a member of '`global namespace'' [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(50,53): error C2065: '_O_RDONLY': undeclared identifier [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(50,65): error C2065: '_O_RDWR': undeclared identifier [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(50,23): error C3861: '_open': identifier not found [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(68,46): error C3861: '_get_osfhandle': identifier not found [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(71,31): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(103,7): error C2039: '_close': is not a member of '`global namespace'' [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
D:\a\DroneDB\DroneDB\vendor\untwine\untwine\MapFile.cpp(103,13): error C3861: '_close': identifier not found [D:\a\DroneDB\DroneDB\build\ddb.vcxproj]
```

I think that the compiler on Windows is more strict than gcc

**Comment by pierotofy** [comment]
No, this should have been fixed with https://github.com/pierotofy/untwine/commit/22a9649c8eed24cb30f6cc0d3948b6c709f99b6f

**Comment by pierotofy** [comment]
Git submodules are so much fun. Should work now.

**Comment by HeDo88TH** [comment]
Obviously on Windows:

```
git clone --recurse-submodules https://github.com/DroneDB/DroneDB.git DroneDB-EPT
cd DroneDB-EPT
gh pr checkout 203
mkdir build
cd build
cmake -DBUILD_TESTING=ON ..
```

gives me

```
CMake Error at CMakeLists.txt:135 (add_library):
  Cannot find source file:

    C:/Users/IT 2/source/repos/DroneDB-EPT/vendor/untwine/untwine/MapFile.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:135 (add_library):
  No SOURCES given to target: ddb
```

The vendor/untwine folder is empty, isn't it a submodule?

**Comment by pierotofy** [comment]
GitHub CI is passing on Windows, so you must be doing something wrong.

Try:

`git submodule update --init`

Or 

`git submodule sync --recursive`

**Pull request merged**
