### PR TITLE
Add ept thumbnails

### PR DESCRIPTION
**Pull request by HeDo88TH**
- [x] Compiles on Windows
 - [x] Compiles on Linux
 - [x] Manual tests on Windows to confirm the functionality/command works
 - [x] Manual tests on Linux to confirm the functionality/command works
 - [x] Manual tests on commands/functionality that might have been affected by these changes.
 - [x] There are no styling changes to unrelated code.

### CODE REVIEW

**Comment by pierotofy** [comment]
@HeDo88TH something is wrong (I suspect your tileScale computation). The rendering are often times warped.

E.g. the brighton beach point cloud's EPT:

```
$ ddb thumbs -i untwine_pointcloud/ept.json -o thumbs -s 1024 --debug
thumbs/ept.jpg
```

Results in: (notice the warping around the building)

image


Correct should be more like:

image

*Triple* check with a variety of datasets if you haven't.

**Comment by HeDo88TH** [comment]
> @HeDo88TH something is wrong (I suspect your tileScale computation). The rendering are often times warped.
> 
> E.g. the brighton beach point cloud's EPT:
> 
> ```
> $ ddb thumbs -i untwine_pointcloud/ept.json -o thumbs -s 1024 --debug
> thumbs/ept.jpg
> ```
> 
> Results in: (notice the warping around the building)
> 
> image
> 
> Correct should be more like:
> 
> image
> 
> _Triple_ check with a variety of datasets if you haven't.

That code was straight from EptTiler, I'll check it out but I supposed that was fine.

**Comment by pierotofy** [comment]
The tiler does not exhibit warping.

image

**Comment by HeDo88TH** [comment]
@pierotofy I'm back from linear algebra class! This is definitely ready for review 🚀

**Pull request merged**
