### PR TITLE
Add PDAL / Point Cloud support

### PR DESCRIPTION
**Pull request by pierotofy**
- Add misc scripts, find pdal cmake
- Add support for point clouds
- Extract polygon/point geometries for point clouds

### CODE REVIEW

**Comment by pierotofy** [comment]
- Still need to setup Windows support.

**Comment by pierotofy** [comment]
```
ddb info /data/drone/brighton2/odm_georeferencing/odm_georeferenced_model.laz
Path: file:///data/drone/brighton2/odm_georeferencing/odm_georeferenced_model.laz
Type: PointCloud (5)
Dimensions: ["X","Y","Z","Intensity","ReturnNumber","NumberOfReturns","ScanDirectionFlag","EdgeOfFlightLine","Classification","ScanAngleRank","UserData","PointSourceId","GpsTime","Red","Green","Blue"]
PointCount: 980110
Projection: PROJCS["WGS 84 / UTM zone 15N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-93],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32615"]]
Modified Time: 1616939034
Size: 5.17 MB
Point Geometry: [[-91.99390815453, 46.84261382285, 156.2540435791] ]
Polygon Geometry: [[-91.99464376021, 46.84215704018, 156.2540435791] [-91.99464376021, 46.84307060067, 156.2540435791] [-91.99317253639, 46.84307060067, 156.2540435791] [-91.99317253639, 46.84215704018, 156.2540435791] [-91.99464376021, 46.84215704018, 156.2540435791] ]
```

**Comment by pierotofy** [comment]
w00t, Windows support.

image

**Comment by pierotofy** [comment]
To add or not to add a unit test...

**Comment by HeDo88TH** [comment]
> To add or not to add a unit test...

This is the question!

BTW we should also remember to add `libpdal-dev`, `pdal` and `python3` dependencies to Dockerfile!
More CMAKE madness to stitch everything together 👍

**Comment by pierotofy** [comment]
Ready for review @HeDo88TH

**Comment by HeDo88TH** [comment]
Compiled, run and tested on windows. It works like a charm 👍

**Pull request merged**
