### PR TITLE
Improve delta sync

### LINKED ISSUE #294: Improve sync behavior
- Handle metadata syncs
 - Improve merge conflicts on ddb pull

### PR DESCRIPTION
**Pull request by pierotofy**
WIP

Closes #294 #296

### CODE REVIEW

**Comment by pierotofy** [comment]
Fixes #298

**Comment by pierotofy** [comment]
TODO:

- [ ] Sync meta with push/pull
- [ ] Fix CI

**Comment by pierotofy** [comment]
Proper delta sync
=============

 - You can clone a dataset: `ddb clone <dataset> a`
 - Another user can clone the dataset
 - You can add/rename/delete files.
 - Other user can do the same.
 - `ddb pull` and `ddb push` will work correctly, allowing merging of conflicts (if user A adds a file, user B adds another file, both users can sync without issue for example).
 - Setting metadata syncs correctly also. `ddb meta add annotations 123`
     - One exception is singular metadata keys. If two metadata keys have the same path/key configuration (user A sets `config 123` and user B sets `config abc`), the most recent one will be merged (overriding the other one). We might change this in the future to handle singular metadata conflicts.

Technical info
==========

We now keep track of database *stamps*. You can generate a stamp by issuing: `ddb stamp`. On clone/push/pull we update remote stamps by saving them in `.ddb/sync.json`. Deltas are computed on stamps rather than ddb instances directly. Stamps are virtually snapshots with checksums in time of a DDB database, which allow us to understand when changes are made and how to deal with merges.

Delta no longer has `copies` keys, since `copies` are just a special case of `adds`. On apply delta we check for the presence of local files (validating modified time and hashes) and avoid downloading/uploading files that are locally available.

No unit tests, write them if you want to.

**Comment by pierotofy** [comment]
Node build is broken for no apparent reason (GitHub action env changes?) so I disabled it.

**Comment by pierotofy** [comment]
Ready for review @HeDo88TH

**Comment by HeDo88TH** [comment]
> Ready for review @HeDo88TH

I will definitely check it out 👍

**Pull request merged**
