### PR TITLE
Add markdown support

### LINKED ISSUE #95: Add support for markdown files
We should add support for markdown files as a new file type.

### PR DESCRIPTION
**Pull request by HeDo88TH**
Closes #95

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Looks good!

**Comment by pierotofy** [comment]
Oh, actually, you missed a few enums here https://github.com/DroneDB/DroneDB/blob/master/nodejs/js/entry.js

**Review by pierotofy — CHANGES_REQUESTED** [review]
Forgot enum

**Comment by HeDo88TH** [comment]
I think we should split the node bindings from the dronedb core, as we did for .NET

**Review by pierotofy — APPROVED** [review]

**Comment by pierotofy** [comment]
Could be done at some point.

**Pull request merged**
