### PR TITLE
Metadata

### LINKED ISSUE #140: Annotations
Users should be able to add geotagged annotations to a dataset (or a directory, or both).

### PR DESCRIPTION
**Pull request by pierotofy**
- [x] Compiles on Windows
 - [x] Compiles on Linux
 - [x] Manual tests on Windows to confirm the functionality/command works
 - [x] Manual tests on Linux to confirm the functionality/command works
 - [x] Manual tests on commands/functionality that might have been affected by these changes.
 
There are some styling changes to unrelated code, due to refactoring.

Closes #140

### CODE REVIEW

**Comment by pierotofy** [comment]
```
[piero:/data/test] 1 $ ddb meta add annotation true
{"data":"true","id":"837637be-cb0a-4832-a162-9389e3dc57b5","mtime":1630965731}
[piero:/data/test] $ ddb meta add annotation 123
{"data":"123","id":"51fd040a-3395-4595-921e-db613b027c8a","mtime":1630965774}
[piero:/data/test] $ ddb meta add annotation 123
{"data":123,"id":"703ee07e-1801-4b20-bf1e-bf274e6cc55d","mtime":1630965938}
[piero:/data/test] $ ddb meta add annotation test
{"data":"test","id":"e1453f43-5477-4298-8b20-ee0625ca04f1","mtime":1630965941}
[piero:/data/test] $ ddb meta add annotation '{"a": null}'
{"data":{"a":null},"id":"d27b6181-06ab-414d-858f-85d4cd03f122","mtime":1630965952}
```

**Comment by pierotofy** [comment]
```
[piero:/data/test] $ ddb meta set config 3455 -p a.txt
{"data":"3455","id":"426e06ed-494e-4351-9ac0-39e6ad00fad3","mtime":1631202390}
```

**Comment by pierotofy** [comment]
```
[piero:/data/test] $ ddb meta get annotations
[{"data":123,"id":"6fff0679-53da-4dc7-b72f-8ef4062dc8b4","mtime":1631200728}]
[piero:/data/test] $ ddb meta add annotation 567
Note: saving metadata as "annotations" (plural)
{"data":567,"id":"4d8a31a7-05cc-4b50-8467-13a3fd3243d5","mtime":1631204511}
[piero:/data/test] $ ddb meta get annotations
[{"data":123,"id":"6fff0679-53da-4dc7-b72f-8ef4062dc8b4","mtime":1631200728},{"data":567,"id":"4d8a31a7-05cc-4b50-8467-13a3fd3243d5","mtime":1631204511}]
[piero:/data/test] $
```

**Comment by pierotofy** [comment]
```
[piero:/data/test] $ ddb add DJI_0019.JPG 
A	DJI_0019.JPG
[piero:/data/test] $ ddb meta add annotation 123 -p DJI_0019.JPG 
Note: saving metadata as "annotations" (plural)
Data: 123
Id: 799e3335-4b68-41b9-a77e-5d82ecf0335a
Mtime: 1631298110
[piero:/data/test] $ ddb meta add annotation 567 -p DJI_0019.JPG 
Note: saving metadata as "annotations" (plural)
Data: 567
Id: f939c76a-9dd7-49b1-8a01-9d818eb0e4e4
Mtime: 1631298117
[piero:/data/test] $ ddb meta set config '{"test": true}'
Data: {"test":true}
Id: 11979f5c-4d8d-4497-8909-14456b7d1ffe
Mtime: 1631298130
[piero:/data/test] $ ddb meta set config '{"test": true}' -p DJI_0019.JPG 
Data: {"test":true}
Id: 1de30d9a-3264-43d7-bb44-3a92ad288bbd
Mtime: 1631298135

[piero:/data/test] $ ddb ls --format json DJI_0019.JPG  | jq '.[0].meta'
{
  "annotations": [
    {
      "data": 123,
      "id": "799e3335-4b68-41b9-a77e-5d82ecf0335a",
      "mtime": 1631298110
    },
    {
      "data": 567,
      "id": "f939c76a-9dd7-49b1-8a01-9d818eb0e4e4",
      "mtime": 1631298117
    }
  ],
  "config": {
    "data": {
      "test": true
    },
    "id": "1de30d9a-3264-43d7-bb44-3a92ad288bbd",
    "mtime": 1631298135
  }
}
```

**Comment by pierotofy** [comment]
```
[piero:/data/test] $ ddb info .
Path: file:///data/test/.
Type: DroneDB (7)
Entries: 6
Mtime: 1631298711
Public: false
Modified Time: 1631372981
Size: 3.75 MB

[piero:/data/test] $ ddb meta add config 123
Note: saving metadata as "configs" (plural)
Data: 123
Id: 81db1de4-f51d-48be-a5c5-0a7dcfa81822
Mtime: 1631395742
[piero:/data/test] $ ddb info .
Path: file:///data/test/.
Type: DroneDB (7)
Entries: 6
Meta: {"configs":[{"data":123,"id":"81db1de4-f51d-48be-a5c5-0a7dcfa81822","mtime":1631395742}]}
Mtime: 1631395742
Public: false
Modified Time: 1631372981
Size: 3.75 MB
```

**Comment by pierotofy** [comment]
Ready for review @HeDo88TH

**Comment by HeDo88TH** [comment]
This is gold 🚀

**Pull request merged**
