### PR TITLE
Share Command

### PR DESCRIPTION
**Pull request by pierotofy**
Current work on `ddb share` is going in this branch.
 - Added parseTag, share command mock.

### CODE REVIEW

**Comment by pierotofy** [comment]
This is good enough as a prototype.

Usage:

```ddb share <files or folders> -t http://<host>:5000/<org>/<dataset>```

**Comment by HeDo88TH** [comment]
> This is good enough for a prototype.
> 
> Usage:
> 
> `ddb share <files or folders> -t http://<host>:5000/<org>/<dataset>`
> 
> See `ddb share --help` for all options.
> 
> Ready for review @HeDo88TH

Nice work, I think that it would be more clear to use it like this:

`ddb share <files or folders> [-t <host>:<port>] <org>/<dataset>`

**Comment by pierotofy** [comment]
Mm, just following the original design document. The tag encodes the host/port. It's a bit like docker. https://docs.docker.com/engine/reference/commandline/tag/#examples

**Comment by HeDo88TH** [comment]
Yes, in that reference It doesn't specify the http or https, just the host and port

**Comment by pierotofy** [comment]
You can omit `http://` and it will default to `https://`.

**Comment by HeDo88TH** [comment]
Great, we can merge!

**Pull request merged**
